name: Curl Status Check

on:
  schedule:
    - cron: "*/1 * * * *" # Runs every minute
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  curl-check:
    runs-on: ubuntu-latest

    steps:
      - name: Perform curl request
        run: curl -o /dev/null -s -w "%{http_code}\n" https://webdario-backend.onrender.com/api/lofi
